# vim ft=yaml
language: python

sudo: required

services:
	- docker

cache:
	- apt

install:
	# make sure we have all needed
	- docker --version
	- docker-compose --version

script:
	- cd docker
	- docker-compose build
	- docker-compose up
	# TODO: run dandi-cli tests addin/enabling those which would talk to this instance
	- :
	- docker-compose down
